export const COURSE_CATEGORIES = [
  "accounting_&_finance",
  "agric_&_food_sciences",
  "architecture_&_urban_plannig",
  "art_&_design",
  "astronomy_&_astrophysics",
  "biology",
  "biotech_&_biomedical_sciences",
  "business_&_managment",
  "chemistry",
  "comp_sci",
  "cyber_&_networking",
  "data_science_&_ai",
  "economics",
  "education_&_teaching",
  "engineering",
  "geography_&_environmental_science",
  "history_&_archeology",
  "law_&_legal_studies",
  "literature_&_linguistics",
  "mathematics",
  "media_&_communications",
  "medicine_&_health_sciences",
  "music_&_performing_arts",
  "pharmacy_&_pharmacology",
  "philosophy_&_ethics",
  "physics",
  "political_science_&_political_relations",
  "psychology",
  "public_health_epidemiology",
  "sociology_social_work",
] as const;

export type CourseCategory = (typeof COURSE_CATEGORIES)[number];
