export const NotificationType = {
  STREAK_MILESTONE: "STREAK_MILESTONE",
  XP_MILESTONE: "XP_MILESTONE",
  TOPIC_MILESTONE: "TOPIC_MILESTONE",
  COURSE_MILESTONE: "COURSE_MILESTONE",
  LEADERBOARD_ACHIEVEMENT: "LEADERBOARD_ACHIEVEMENT",
  TOPIC_COMPLETED: "TOPIC_COMPLETED",
  COURSE_COMPLETED: "COURSE_COMPLETED",
  QUIZ_PASSED: "QUIZ_PASSED",
  QUIZ_FAILED: "QUIZ_FAILED",
  STREAK_AT_RISK: "STREAK_AT_RISK",
  STUDY_REMINDER: "STUDY_REMINDER",
} as const;
